REM Deletes files no longer present, rooted in the current directory
DEL /F ".\Deleted File.txt"
DEL /F ".\Moved and Edited File.txt"
DEL /F ".\Moved and Unedited File.txt"
DEL /F ".\A Subdirectory\Cross-Moved and Edited File.txt"
DEL /F ".\A Subdirectory\Cross-Moved and Unedited File.txt"
DEL /F ".\A Subdirectory\Deleted File.txt"
DEL /F ".\A Subdirectory\Moved and Edited File.txt"
DEL /F ".\A Subdirectory\Moved and Unedited File.txt"
DEL /F ".\Deleted Subdirectory\Deleted File.txt"
RMDIR ".\Deleted Subdirectory"
DEL /F ".\Moved Subdirectory\Deleted File.txt"
DEL /F ".\Moved Subdirectory\Moved and Edited File.txt"
DEL /F ".\Moved Subdirectory\Moved and Unedited File.txt"
RMDIR ".\Moved Subdirectory"
