REM Prepares the previous state of the backup set, rooted in the current directory, for having new files copied over it
MKDIR ".\Created Subdirectory"
MKDIR ".\New Moved Subdirectory"
REM Transfers copied files to temporary dirs
MKDIR ".\.tmp"
COPY ".\Another Unmoved and Unedited File.txt" ".\.tmp\Another Unmoved and Unedited File.txt"
MOVE ".\Moved and Unedited File.txt" ".\.tmp\Moved and Unedited File.txt"
MOVE ".\Swapped File.txt" ".\.tmp\Swapped File.txt"
COPY ".\Unmoved and Unedited File.txt" ".\.tmp\Unmoved and Unedited File.txt"
MKDIR ".\A Subdirectory\.tmp"
MOVE ".\A Subdirectory\Cross-Moved and Unedited File.txt" ".\A Subdirectory\.tmp\Cross-Moved and Unedited File.txt"
MOVE ".\A Subdirectory\Swapped File.txt" ".\A Subdirectory\.tmp\Swapped File.txt"
MKDIR ".\Moved Subdirectory\.tmp"
MOVE ".\Moved Subdirectory\Moved and Unedited File.txt" ".\Moved Subdirectory\.tmp\Moved and Unedited File.txt"
REM Transfers copied files to final destination
MOVE ".\.tmp\Another Unmoved and Unedited File.txt" ".\Copied Another Unmoved and Unedited File.txt"
COPY ".\.tmp\Moved and Unedited File.txt" ".\New Moved and Unedited File.txt"
MOVE ".\.tmp\Moved and Unedited File.txt" ".\A Subdirectory\New Moved and Unedited File.txt"
MOVE ".\.tmp\Swapped File.txt" ".\A Subdirectory\Swapped File.txt"
COPY ".\.tmp\Unmoved and Unedited File.txt" ".\Copied Unmoved and Unedited File.txt"
COPY ".\.tmp\Unmoved and Unedited File.txt" ".\A Subdirectory\Copied Unmoved & Unedited File.txt"
MOVE ".\.tmp\Unmoved and Unedited File.txt" ".\New Moved Subdirectory\Cross-Copied Unmoved & Unedited File.txt"
COPY ".\A Subdirectory\.tmp\Cross-Moved and Unedited File.txt" ".\Cross-Moved and Unedited File.txt"
MOVE ".\A Subdirectory\.tmp\Cross-Moved and Unedited File.txt" ".\New Moved Subdirectory\Double Cross-Moved and Unedited File.txt"
MOVE ".\A Subdirectory\.tmp\Swapped File.txt" ".\Swapped File.txt"
MOVE ".\Moved Subdirectory\.tmp\Moved and Unedited File.txt" ".\New Moved Subdirectory\Moved and Unedited File.txt"
REM Clears away deleted objects and temporary dirs
DEL /F ".\Deleted File.txt"
DEL /F ".\Moved and Edited File.txt"
DEL /F ".\A Subdirectory\Cross-Moved and Edited File.txt"
DEL /F ".\A Subdirectory\Deleted File.txt"
DEL /F ".\A Subdirectory\Moved and Edited File.txt"
DEL /F ".\A Subdirectory\Moved and Unedited File.txt"
RMDIR ".\A Subdirectory\.tmp"
DEL /F ".\Deleted Subdirectory\Deleted File.txt"
RMDIR ".\Deleted Subdirectory"
DEL /F ".\Moved Subdirectory\Deleted File.txt"
DEL /F ".\Moved Subdirectory\Moved and Edited File.txt"
RMDIR ".\Moved Subdirectory\.tmp"
RMDIR ".\Moved Subdirectory"
RMDIR ".\.tmp"
