# Prepares the previous state of the backup set, rooted in the current directory, for having the updated files copied over it
mkdir "./Created Subdirectory"
mkdir "./New Moved Subdirectory"
# Transfers copied files to temporary dirs
mkdir "./.tmp"
cp "./Another Unmoved and Unedited File.txt" "./.tmp/Another Unmoved and Unedited File.txt"
cp "./Lying File.txt" "./.tmp/Lying File.txt"
mv "./Moved and Unedited File.txt" "./.tmp/Moved and Unedited File.txt"
mv "./Swapped File.txt" "./.tmp/Swapped File.txt"
cp "./Unmoved and Unedited File.txt" "./.tmp/Unmoved and Unedited File.txt"
mkdir "./A Subdirectory/.tmp"
mv "./A Subdirectory/Cross-Moved and Unedited File.txt" "./A Subdirectory/.tmp/Cross-Moved and Unedited File.txt"
mv "./A Subdirectory/Moved and Unedited File.txt" "./A Subdirectory/.tmp/Moved and Unedited File.txt"
mv "./A Subdirectory/Swapped File.txt" "./A Subdirectory/.tmp/Swapped File.txt"
mkdir "./Moved Subdirectory/.tmp"
mv "./Moved Subdirectory/Moved and Unedited File.txt" "./Moved Subdirectory/.tmp/Moved and Unedited File.txt"
# Transfers copied files to final destination
mv "./.tmp/Another Unmoved and Unedited File.txt" "./Copied Another Unmoved and Unedited File.txt"
mv "./.tmp/Lying File.txt" "./Created Subdirectory/New Moved Lying File.txt"
mv "./.tmp/Moved and Unedited File.txt" "./New Moved and Unedited File.txt"
mv "./.tmp/Swapped File.txt" "./A Subdirectory/Swapped File.txt"
cp "./.tmp/Unmoved and Unedited File.txt" "./Copied Unmoved and Unedited File.txt"
cp "./.tmp/Unmoved and Unedited File.txt" "./A Subdirectory/Copied Unmoved & Unedited File.txt"
mv "./.tmp/Unmoved and Unedited File.txt" "./New Moved Subdirectory/Cross-Copied Unmoved & Unedited File.txt"
cp "./A Subdirectory/.tmp/Cross-Moved and Unedited File.txt" "./Cross-Moved and Unedited File.txt"
mv "./A Subdirectory/.tmp/Cross-Moved and Unedited File.txt" "./New Moved Subdirectory/Double Cross-Moved and Unedited File.txt"
mv "./A Subdirectory/.tmp/Moved and Unedited File.txt" "./A Subdirectory/New Moved and Unedited File.txt"
mv "./A Subdirectory/.tmp/Swapped File.txt" "./Swapped File.txt"
mv "./Moved Subdirectory/.tmp/Moved and Unedited File.txt" "./New Moved Subdirectory/Moved and Unedited File.txt"
# Clears away deleted objects and temporary dirs
rm -f "./Deleted File.txt"
rm -f "./Moved and Edited File.txt"
rm -f "./A Subdirectory/Cross-Moved and Edited File.txt"
rm -f "./A Subdirectory/Deleted File.txt"
rm -f "./A Subdirectory/Moved Lying File.txt"
rm -f "./A Subdirectory/Moved and Edited File.txt"
rmdir "./A Subdirectory/.tmp"
rm -f "./Deleted Subdirectory/Deleted File.txt"
rmdir "./Deleted Subdirectory"
rm -f "./Moved Subdirectory/Deleted File.txt"
rm -f "./Moved Subdirectory/Moved and Edited File.txt"
rmdir "./Moved Subdirectory/.tmp"
rmdir "./Moved Subdirectory"
rmdir "./.tmp"
