REM Prepares the previous state of the backup set, rooted in the current directory, for having new files copied over it
MKDIR ".\Created Subdirectory"
MKDIR ".\New Moved Subdirectory"
COPY ".\Another Unmoved and Unedited File.txt" ".\Copied Another Unmoved and Unedited File.txt"
DEL /F ".\Deleted File.txt"
DEL /F ".\Moved and Edited File.txt"
COPY ".\Moved and Unedited File.txt" ".\New Moved and Unedited File.txt"
MOVE ".\Moved and Unedited File.txt" ".\A Subdirectory\New Moved and Unedited File.txt"
COPY ".\Unmoved and Unedited File.txt" ".\Copied Unmoved and Unedited File.txt"
COPY ".\Unmoved and Unedited File.txt" ".\A Subdirectory\Copied Unmoved & Unedited File.txt"
COPY ".\Unmoved and Unedited File.txt" ".\New Moved Subdirectory\Cross-Copied Unmoved & Unedited File.txt"
DEL /F ".\A Subdirectory\Cross-Moved and Edited File.txt"
COPY ".\A Subdirectory\Cross-Moved and Unedited File.txt" ".\Cross-Moved and Unedited File.txt"
MOVE ".\A Subdirectory\Cross-Moved and Unedited File.txt" ".\New Moved Subdirectory\Double Cross-Moved and Unedited File.txt"
DEL /F ".\A Subdirectory\Deleted File.txt"
DEL /F ".\A Subdirectory\Moved and Edited File.txt"
DEL /F ".\A Subdirectory\Moved and Unedited File.txt"
DEL /F ".\Deleted Subdirectory\Deleted File.txt"
RMDIR ".\Deleted Subdirectory"
DEL /F ".\Moved Subdirectory\Deleted File.txt"
DEL /F ".\Moved Subdirectory\Moved and Edited File.txt"
MOVE ".\Moved Subdirectory\Moved and Unedited File.txt" ".\New Moved Subdirectory\Moved and Unedited File.txt"
RMDIR ".\Moved Subdirectory"
