#!/bin/sh
export EXEC_DIR="$(realpath "$(dirname "${0}")")"

ln -s "${EXEC_DIR}" /tmp/TransparentBackup

for t in "src0" "src1"
do
  rm -rf tests.in/00/${t}
  mkdir tests.in/00/${t}
  tar -xf tests.in/00/${t}.tar --directory tests.in/00/${t}

  mkdir --parents tests.new/00/${t}
done

for s in BashScript ZippingPythonScript
do
  ./transparentbackup.py -b /tmp/TransparentBackup/tests.in/00/src0 -o tests.new/00/src0 -s ${s} --skip ".NOBACKUP"
  ./transparentbackup.py -b /tmp/TransparentBackup/tests.in/00/src1 -o tests.new/00/src1 -s ${s} --skip ".NOBACKUP" -d tests.new/00/src0/!fullstate.dtml
done

meld tests.out tests.new

rm /tmp/TransparentBackup
