# Copies files to be backed up to the current directory
mkdir --parents "."
cp --no-dereference --preserve=all "/tmp/TransparentBackup/tests.in/00/src0/./Another Unmoved and Unedited File.txt" "./Another Unmoved and Unedited File.txt"
cp --no-dereference --preserve=all "/tmp/TransparentBackup/tests.in/00/src0/./Deleted File.txt" "./Deleted File.txt"
cp --no-dereference --preserve=all "/tmp/TransparentBackup/tests.in/00/src0/./Moved and Edited File.txt" "./Moved and Edited File.txt"
cp --no-dereference --preserve=all "/tmp/TransparentBackup/tests.in/00/src0/./Moved and Unedited File.txt" "./Moved and Unedited File.txt"
cp --no-dereference --preserve=all "/tmp/TransparentBackup/tests.in/00/src0/./Swapped File.txt" "./Swapped File.txt"
cp --no-dereference --preserve=all "/tmp/TransparentBackup/tests.in/00/src0/./Unmoved and Edited File.txt" "./Unmoved and Edited File.txt"
cp --no-dereference --preserve=all "/tmp/TransparentBackup/tests.in/00/src0/./Unmoved and Unedited File.txt" "./Unmoved and Unedited File.txt"
mkdir --parents "./A Subdirectory"
cp --no-dereference --preserve=all "/tmp/TransparentBackup/tests.in/00/src0/./A Subdirectory/Cross-Moved and Edited File.txt" "./A Subdirectory/Cross-Moved and Edited File.txt"
cp --no-dereference --preserve=all "/tmp/TransparentBackup/tests.in/00/src0/./A Subdirectory/Cross-Moved and Unedited File.txt" "./A Subdirectory/Cross-Moved and Unedited File.txt"
cp --no-dereference --preserve=all "/tmp/TransparentBackup/tests.in/00/src0/./A Subdirectory/Moved and Unedited File.txt" "./A Subdirectory/Moved and Unedited File.txt"
cp --no-dereference --preserve=all "/tmp/TransparentBackup/tests.in/00/src0/./A Subdirectory/Swapped File.txt" "./A Subdirectory/Swapped File.txt"
mkdir --parents "./Deleted Subdirectory"
cp --no-dereference --preserve=all "/tmp/TransparentBackup/tests.in/00/src0/./Deleted Subdirectory/Deleted File.txt" "./Deleted Subdirectory/Deleted File.txt"
mkdir --parents "./Moved Subdirectory"
cp --no-dereference --preserve=all "/tmp/TransparentBackup/tests.in/00/src0/./Moved Subdirectory/Deleted File.txt" "./Moved Subdirectory/Deleted File.txt"
cp --no-dereference --preserve=all "/tmp/TransparentBackup/tests.in/00/src0/./Moved Subdirectory/Moved and Edited File.txt" "./Moved Subdirectory/Moved and Edited File.txt"
cp --no-dereference --preserve=all "/tmp/TransparentBackup/tests.in/00/src0/./Moved Subdirectory/Moved and Unedited File.txt" "./Moved Subdirectory/Moved and Unedited File.txt"
# Diff set file count: 15
# Diff set total bytes: 1156
