# Copies files to be backed up to the current directory
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./Another Unmoved and Unedited File.txt" "./Another Unmoved and Unedited File.txt"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./Deleted File.txt" "./Deleted File.txt"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./Moved and Edited File.txt" "./Moved and Edited File.txt"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./Moved and Unedited File.txt" "./Moved and Unedited File.txt"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./Swapped File.txt" "./Swapped File.txt"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./Unmoved and Edited File.txt" "./Unmoved and Edited File.txt"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./Unmoved and Unedited File.txt" "./Unmoved and Unedited File.txt"
mkdir "./A Subdirectory"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./A Subdirectory/Cross-Moved and Edited File.txt" "./A Subdirectory/Cross-Moved and Edited File.txt"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./A Subdirectory/Cross-Moved and Unedited File.txt" "./A Subdirectory/Cross-Moved and Unedited File.txt"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./A Subdirectory/Deleted File.txt" "./A Subdirectory/Deleted File.txt"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./A Subdirectory/Moved and Edited File.txt" "./A Subdirectory/Moved and Edited File.txt"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./A Subdirectory/Moved and Unedited File.txt" "./A Subdirectory/Moved and Unedited File.txt"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./A Subdirectory/Swapped File.txt" "./A Subdirectory/Swapped File.txt"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./A Subdirectory/Unmoved & Unedited File.txt" "./A Subdirectory/Unmoved & Unedited File.txt"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./A Subdirectory/Unmoved and Edited File.txt" "./A Subdirectory/Unmoved and Edited File.txt"
mkdir "./Deleted Subdirectory"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./Deleted Subdirectory/Deleted File.txt" "./Deleted Subdirectory/Deleted File.txt"
mkdir "./Moved Subdirectory"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./Moved Subdirectory/Deleted File.txt" "./Moved Subdirectory/Deleted File.txt"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./Moved Subdirectory/Moved and Edited File.txt" "./Moved Subdirectory/Moved and Edited File.txt"
cp "/cygdrive/i/--Geoff--/Software/apps/Transparent Backup.trunk/tests.in/00/src0/./Moved Subdirectory/Moved and Unedited File.txt" "./Moved Subdirectory/Moved and Unedited File.txt"
# Diff set file count: 19
# Diff set total bytes: 1380
